// <auto-generated />
using System;
using HolaCare.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HolaCare.Migrations
{
    [DbContext(typeof(DBHolaContext))]
    [Migration("20210102164523_mit3")]
    partial class mit3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("HolaCare.Models.Blog", b =>
                {
                    b.Property<string>("IDBlog")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisabledBlog")
                        .HasColumnType("bit");

                    b.Property<string>("Heading")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDComposer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDTopic")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("IDBlog");

                    b.HasIndex("IDTopic");

                    b.HasIndex("IDUser");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("HolaCare.Models.Brand", b =>
                {
                    b.Property<string>("IDBrand")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionBrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisabledBrand")
                        .HasColumnType("bit");

                    b.HasKey("IDBrand");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("HolaCare.Models.CommentBlog", b =>
                {
                    b.Property<string>("IDCmtBlog")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ComposerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisabledCmtblog")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDBlog")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeCmtBlog")
                        .HasColumnType("datetime2");

                    b.HasKey("IDCmtBlog");

                    b.HasIndex("IDBlog");

                    b.ToTable("CommentBlogs");
                });

            modelBuilder.Entity("HolaCare.Models.CommentProduct", b =>
                {
                    b.Property<string>("IDCmtProduct")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ComposerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisabledCmtProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDProduct")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeCmtProduct")
                        .HasColumnType("datetime2");

                    b.HasKey("IDCmtProduct");

                    b.HasIndex("IDProduct");

                    b.ToTable("CommentProducts");
                });

            modelBuilder.Entity("HolaCare.Models.IngreProduct", b =>
                {
                    b.Property<string>("IDIngre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ID3code")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDIngre", "ID3code");

                    b.HasIndex("ID3code");

                    b.ToTable("IngreProducts");
                });

            modelBuilder.Entity("HolaCare.Models.IngredientDetail", b =>
                {
                    b.Property<string>("IDIngre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Function")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameIngre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PointIngre")
                        .HasColumnType("real");

                    b.Property<string>("Uses")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDIngre");

                    b.ToTable("IngredientDetails");
                });

            modelBuilder.Entity("HolaCare.Models.Point", b =>
                {
                    b.Property<string>("IDPoint")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDSkinType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<float>("PAcneType")
                        .HasColumnType("real");

                    b.Property<float>("PDailyHabit")
                        .HasColumnType("real");

                    b.Property<float>("PMealHabit")
                        .HasColumnType("real");

                    b.Property<float>("PPastUsing")
                        .HasColumnType("real");

                    b.Property<float>("PTotal")
                        .HasColumnType("real");

                    b.HasKey("IDPoint");

                    b.HasIndex("IDSkinType");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("HolaCare.Models.Product", b =>
                {
                    b.Property<string>("ID3code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisabledPro")
                        .HasColumnType("bit");

                    b.Property<string>("IDBrand")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDProductType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDSkintype")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Linktobuy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PointProduct")
                        .HasColumnType("real");

                    b.HasKey("ID3code");

                    b.HasIndex("IDBrand");

                    b.HasIndex("IDProductType");

                    b.HasIndex("IDSkintype");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("HolaCare.Models.ProductType", b =>
                {
                    b.Property<string>("IDProductType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisabledProductType")
                        .HasColumnType("bit");

                    b.Property<string>("NameProductType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDProductType");

                    b.ToTable("ProductType");
                });

            modelBuilder.Entity("HolaCare.Models.SkinType", b =>
                {
                    b.Property<string>("IDSkinType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisabledSkinType")
                        .HasColumnType("bit");

                    b.Property<string>("NameSkinType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDSkinType");

                    b.ToTable("SkinTypes");
                });

            modelBuilder.Entity("HolaCare.Models.TopicBlog", b =>
                {
                    b.Property<string>("IDTopicBlog")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("DisabledTopicBlog")
                        .HasColumnType("bit");

                    b.Property<string>("NameTopicBlog")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDTopicBlog");

                    b.ToTable("TopicBlogs");
                });

            modelBuilder.Entity("HolaCare.Models.User", b =>
                {
                    b.Property<string>("IDUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Authen")
                        .HasColumnType("bit");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Male")
                        .HasColumnType("bit");

                    b.Property<string>("Pass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PointIDPoint")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUser");

                    b.HasIndex("PointIDPoint");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HolaCare.Models.Blog", b =>
                {
                    b.HasOne("HolaCare.Models.TopicBlog", "TopicBlog")
                        .WithMany("Blogs")
                        .HasForeignKey("IDTopic");

                    b.HasOne("HolaCare.Models.User", "User")
                        .WithMany("Blogs")
                        .HasForeignKey("IDUser");

                    b.Navigation("TopicBlog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HolaCare.Models.CommentBlog", b =>
                {
                    b.HasOne("HolaCare.Models.Blog", "Blog")
                        .WithMany("CommentBlogs")
                        .HasForeignKey("IDBlog");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("HolaCare.Models.CommentProduct", b =>
                {
                    b.HasOne("HolaCare.Models.Product", "Product")
                        .WithMany("CommentProducts")
                        .HasForeignKey("IDProduct");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HolaCare.Models.IngreProduct", b =>
                {
                    b.HasOne("HolaCare.Models.Product", "Product")
                        .WithMany("IngreProducts")
                        .HasForeignKey("ID3code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HolaCare.Models.IngredientDetail", "IngredientDetail")
                        .WithMany("IngreProducts")
                        .HasForeignKey("IDIngre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientDetail");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HolaCare.Models.Point", b =>
                {
                    b.HasOne("HolaCare.Models.SkinType", "Skintype")
                        .WithMany("Points")
                        .HasForeignKey("IDSkinType");

                    b.Navigation("Skintype");
                });

            modelBuilder.Entity("HolaCare.Models.Product", b =>
                {
                    b.HasOne("HolaCare.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("IDBrand");

                    b.HasOne("HolaCare.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("IDProductType");

                    b.HasOne("HolaCare.Models.SkinType", "Skintype")
                        .WithMany("Products")
                        .HasForeignKey("IDSkintype");

                    b.Navigation("Brand");

                    b.Navigation("ProductType");

                    b.Navigation("Skintype");
                });

            modelBuilder.Entity("HolaCare.Models.User", b =>
                {
                    b.HasOne("HolaCare.Models.Point", "Point")
                        .WithMany()
                        .HasForeignKey("PointIDPoint");

                    b.Navigation("Point");
                });

            modelBuilder.Entity("HolaCare.Models.Blog", b =>
                {
                    b.Navigation("CommentBlogs");
                });

            modelBuilder.Entity("HolaCare.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HolaCare.Models.IngredientDetail", b =>
                {
                    b.Navigation("IngreProducts");
                });

            modelBuilder.Entity("HolaCare.Models.Product", b =>
                {
                    b.Navigation("CommentProducts");

                    b.Navigation("IngreProducts");
                });

            modelBuilder.Entity("HolaCare.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HolaCare.Models.SkinType", b =>
                {
                    b.Navigation("Points");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("HolaCare.Models.TopicBlog", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("HolaCare.Models.User", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
