// <auto-generated />
using System;
using Express.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Express.Migrations
{
    [DbContext(typeof(DBExpressContext))]
    [Migration("20210616183746_chanvcl1")]
    partial class chanvcl1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Express.Models.Bill", b =>
                {
                    b.Property<Guid>("IDBill")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceiveAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SendAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShippingDone")
                        .HasColumnType("bit");

                    b.Property<float>("ShippingFee")
                        .HasColumnType("real");

                    b.Property<string>("ShippingTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Userid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("weight")
                        .HasColumnType("real");

                    b.HasKey("IDBill");

                    b.HasIndex("Userid");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Express.Models.BillStatusDetail", b =>
                {
                    b.Property<Guid>("IDStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Billid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PostReceive")
                        .HasColumnType("bit");

                    b.Property<bool>("Prepair")
                        .HasColumnType("bit");

                    b.Property<bool>("ShipReceive")
                        .HasColumnType("bit");

                    b.Property<bool>("Shipping")
                        .HasColumnType("bit");

                    b.Property<bool>("ShippingDone")
                        .HasColumnType("bit");

                    b.Property<bool>("ShippingToC")
                        .HasColumnType("bit");

                    b.HasKey("IDStatus");

                    b.HasIndex("Billid")
                        .IsUnique();

                    b.ToTable("BillStatusDetails");
                });

            modelBuilder.Entity("Express.Models.CommissionsRealTime", b =>
                {
                    b.Property<Guid>("IDComRT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<Guid>("Billid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDComR")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("IDComRT");

                    b.HasIndex("Billid")
                        .IsUnique();

                    b.HasIndex("IDComR");

                    b.ToTable("CommissionsRealTimes");
                });

            modelBuilder.Entity("Express.Models.CommissionsRule", b =>
                {
                    b.Property<Guid>("IDComR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ComPerBill")
                        .HasColumnType("real");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("IDCompany")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IDComR");

                    b.HasIndex("IDCompany");

                    b.ToTable("CommissionsRules");
                });

            modelBuilder.Entity("Express.Models.Districts", b =>
                {
                    b.Property<Guid>("IDDistrict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CentralDistrict")
                        .HasColumnType("bit");

                    b.Property<string>("DistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Proid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IDDistrict");

                    b.HasIndex("Proid");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("Express.Models.Provinces", b =>
                {
                    b.Property<Guid>("IDProvince")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CentralProvince")
                        .HasColumnType("bit");

                    b.Property<string>("ProvinceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDProvince");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("Express.Models.ShipCompany", b =>
                {
                    b.Property<Guid>("IDCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisterDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubDisid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IDCompany");

                    b.HasIndex("SubDisid")
                        .IsUnique();

                    b.ToTable("ShipCompanies");
                });

            modelBuilder.Entity("Express.Models.ShipDiscount", b =>
                {
                    b.Property<Guid>("IDDis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Compid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ValueDis")
                        .HasColumnType("real");

                    b.HasKey("IDDis");

                    b.HasIndex("Compid");

                    b.ToTable("ShipDiscounts");
                });

            modelBuilder.Entity("Express.Models.ShippingFee", b =>
                {
                    b.Property<Guid>("IDFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Compid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<float>("LienvungDB_Kgthem_Fast")
                        .HasColumnType("real");

                    b.Property<float>("LienvungDB_Kgthem_Low")
                        .HasColumnType("real");

                    b.Property<float>("LienvungDB_Ngoaithanh_Fast")
                        .HasColumnType("real");

                    b.Property<float>("LienvungDB_Ngoaithanh_Low")
                        .HasColumnType("real");

                    b.Property<float>("LienvungDB_Noithanh_Fast")
                        .HasColumnType("real");

                    b.Property<float>("LienvungDB_Noithanh_Low")
                        .HasColumnType("real");

                    b.Property<float>("Lienvung_Kgthem_Fast")
                        .HasColumnType("real");

                    b.Property<float>("Lienvung_Kgthem_Low")
                        .HasColumnType("real");

                    b.Property<float>("Lienvung_Ngoaithanh_Fast")
                        .HasColumnType("real");

                    b.Property<float>("Lienvung_Ngoaithanh_Low")
                        .HasColumnType("real");

                    b.Property<float>("Lienvung_Noithanh_Fast")
                        .HasColumnType("real");

                    b.Property<float>("Lienvung_Noithanh_Low")
                        .HasColumnType("real");

                    b.Property<float>("MaxKg")
                        .HasColumnType("real");

                    b.Property<float>("Noitinh_Kgthem")
                        .HasColumnType("real");

                    b.Property<float>("Noitinh_Ngoaithanh")
                        .HasColumnType("real");

                    b.Property<float>("Noitinh_Noithanh")
                        .HasColumnType("real");

                    b.Property<string>("Noitinh_TGGiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoivungDB_TGGiao_Fast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoivungDB_TGGiao_Low")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Noivung_Kgthem")
                        .HasColumnType("real");

                    b.Property<float>("Noivung_Ngoaithanh")
                        .HasColumnType("real");

                    b.Property<float>("Noivung_Noithanh")
                        .HasColumnType("real");

                    b.Property<string>("Noivung_TGGiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Noivung_TGGiao_Fast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Noivung_TGGiao_Low")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDFee");

                    b.HasIndex("Compid");

                    b.ToTable("ShippingFees");
                });

            modelBuilder.Entity("Express.Models.SubDistricts", b =>
                {
                    b.Property<Guid>("IDSubDistrict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Disid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubDistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDSubDistrict");

                    b.HasIndex("Disid");

                    b.ToTable("SubDistricts");
                });

            modelBuilder.Entity("Express.Models.Users", b =>
                {
                    b.Property<Guid>("IDUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Authen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubDisid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUser");

                    b.HasIndex("SubDisid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Express.Models.Bill", b =>
                {
                    b.HasOne("Express.Models.Users", "User")
                        .WithMany("Bills")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Express.Models.BillStatusDetail", b =>
                {
                    b.HasOne("Express.Models.Bill", "Bill")
                        .WithOne("StatusDetail")
                        .HasForeignKey("Express.Models.BillStatusDetail", "Billid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Express.Models.CommissionsRealTime", b =>
                {
                    b.HasOne("Express.Models.Bill", "Bill")
                        .WithOne("CommisstionsRealTime")
                        .HasForeignKey("Express.Models.CommissionsRealTime", "Billid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Express.Models.CommissionsRule", "CommissionsRule")
                        .WithMany("CommisstionsRealTimes")
                        .HasForeignKey("IDComR")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("CommissionsRule");
                });

            modelBuilder.Entity("Express.Models.CommissionsRule", b =>
                {
                    b.HasOne("Express.Models.ShipCompany", "ShipCompany")
                        .WithMany("CommissionsRules")
                        .HasForeignKey("IDCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipCompany");
                });

            modelBuilder.Entity("Express.Models.Districts", b =>
                {
                    b.HasOne("Express.Models.Provinces", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("Proid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Express.Models.ShipCompany", b =>
                {
                    b.HasOne("Express.Models.SubDistricts", "SubDistrict")
                        .WithOne("ShipCompany")
                        .HasForeignKey("Express.Models.ShipCompany", "SubDisid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubDistrict");
                });

            modelBuilder.Entity("Express.Models.ShipDiscount", b =>
                {
                    b.HasOne("Express.Models.ShipCompany", "ShipCompany")
                        .WithMany("ShipDiscounts")
                        .HasForeignKey("Compid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipCompany");
                });

            modelBuilder.Entity("Express.Models.ShippingFee", b =>
                {
                    b.HasOne("Express.Models.ShipCompany", "ShipCompany")
                        .WithMany("ShippingFees")
                        .HasForeignKey("Compid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipCompany");
                });

            modelBuilder.Entity("Express.Models.SubDistricts", b =>
                {
                    b.HasOne("Express.Models.Districts", "District")
                        .WithMany("SubDistricts")
                        .HasForeignKey("Disid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Express.Models.Users", b =>
                {
                    b.HasOne("Express.Models.SubDistricts", "SubDistrict")
                        .WithOne("User")
                        .HasForeignKey("Express.Models.Users", "SubDisid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubDistrict");
                });

            modelBuilder.Entity("Express.Models.Bill", b =>
                {
                    b.Navigation("CommisstionsRealTime");

                    b.Navigation("StatusDetail");
                });

            modelBuilder.Entity("Express.Models.CommissionsRule", b =>
                {
                    b.Navigation("CommisstionsRealTimes");
                });

            modelBuilder.Entity("Express.Models.Districts", b =>
                {
                    b.Navigation("SubDistricts");
                });

            modelBuilder.Entity("Express.Models.Provinces", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Express.Models.ShipCompany", b =>
                {
                    b.Navigation("CommissionsRules");

                    b.Navigation("ShipDiscounts");

                    b.Navigation("ShippingFees");
                });

            modelBuilder.Entity("Express.Models.SubDistricts", b =>
                {
                    b.Navigation("ShipCompany");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Express.Models.Users", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
