// <auto-generated />
using Express.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Express.Migrations
{
    [DbContext(typeof(DBExpressContext))]
    [Migration("20210618041057_innt")]
    partial class innt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Express.Models.Bill", b =>
                {
                    b.Property<string>("IDBill")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Compid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiveAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceivePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SendAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SendPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShippingDone")
                        .HasColumnType("bit");

                    b.Property<float>("ShippingFee")
                        .HasColumnType("real");

                    b.Property<string>("ShippingTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Userid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("weight")
                        .HasColumnType("real");

                    b.HasKey("IDBill");

                    b.HasIndex("Userid");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Express.Models.BillStatusDetail", b =>
                {
                    b.Property<string>("IDStatus")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Billid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("PostReceive")
                        .HasColumnType("bit");

                    b.Property<bool>("Prepair")
                        .HasColumnType("bit");

                    b.Property<bool>("ShipReceive")
                        .HasColumnType("bit");

                    b.Property<bool>("Shipping")
                        .HasColumnType("bit");

                    b.Property<bool>("ShippingDone")
                        .HasColumnType("bit");

                    b.Property<bool>("ShippingToC")
                        .HasColumnType("bit");

                    b.HasKey("IDStatus");

                    b.HasIndex("Billid")
                        .IsUnique()
                        .HasFilter("[Billid] IS NOT NULL");

                    b.ToTable("BillStatusDetails");
                });

            modelBuilder.Entity("Express.Models.CommissionsRealTime", b =>
                {
                    b.Property<string>("IDComRT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("Billid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDComR")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("IDComRT");

                    b.HasIndex("Billid")
                        .IsUnique()
                        .HasFilter("[Billid] IS NOT NULL");

                    b.HasIndex("IDComR");

                    b.ToTable("CommissionsRealTimes");
                });

            modelBuilder.Entity("Express.Models.CommissionsRule", b =>
                {
                    b.Property<string>("IDComR")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("ComPerBill")
                        .HasColumnType("real");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("IDCompany")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDComR");

                    b.HasIndex("IDCompany");

                    b.ToTable("CommissionsRules");
                });

            modelBuilder.Entity("Express.Models.Districts", b =>
                {
                    b.Property<string>("IDDistrict")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CentralDistrict")
                        .HasColumnType("bit");

                    b.Property<string>("DistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proid")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDDistrict");

                    b.HasIndex("Proid");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("Express.Models.Provinces", b =>
                {
                    b.Property<string>("IDProvince")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CentralProvince")
                        .HasColumnType("bit");

                    b.Property<string>("ProvinceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDProvince");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("Express.Models.ShipCompany", b =>
                {
                    b.Property<string>("IDCompany")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ComAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisterDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubDisid")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IDCompany");

                    b.HasIndex("SubDisid")
                        .IsUnique()
                        .HasFilter("[SubDisid] IS NOT NULL");

                    b.ToTable("ShipCompanies");
                });

            modelBuilder.Entity("Express.Models.ShipDiscount", b =>
                {
                    b.Property<string>("IDDis")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Compid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ValueDis")
                        .HasColumnType("real");

                    b.HasKey("IDDis");

                    b.HasIndex("Compid");

                    b.ToTable("ShipDiscounts");
                });

            modelBuilder.Entity("Express.Models.ShippingFee", b =>
                {
                    b.Property<string>("IDFee")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Compid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<float>("MaxKg")
                        .HasColumnType("real");

                    b.Property<string>("NameFee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<float>("PricePerKg")
                        .HasColumnType("real");

                    b.Property<string>("TGGiao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDFee");

                    b.HasIndex("Compid");

                    b.ToTable("ShippingFees");
                });

            modelBuilder.Entity("Express.Models.SubDistricts", b =>
                {
                    b.Property<string>("IDSubDistrict")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Disid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubDistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDSubDistrict");

                    b.HasIndex("Disid");

                    b.ToTable("SubDistricts");
                });

            modelBuilder.Entity("Express.Models.Users", b =>
                {
                    b.Property<string>("IDUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Authen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubDisid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUser");

                    b.HasIndex("SubDisid")
                        .IsUnique()
                        .HasFilter("[SubDisid] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Express.Models.Bill", b =>
                {
                    b.HasOne("Express.Models.Users", "User")
                        .WithMany("Bills")
                        .HasForeignKey("Userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Express.Models.BillStatusDetail", b =>
                {
                    b.HasOne("Express.Models.Bill", "Bill")
                        .WithOne("StatusDetail")
                        .HasForeignKey("Express.Models.BillStatusDetail", "Billid");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Express.Models.CommissionsRealTime", b =>
                {
                    b.HasOne("Express.Models.Bill", "Bill")
                        .WithOne("CommisstionsRealTime")
                        .HasForeignKey("Express.Models.CommissionsRealTime", "Billid");

                    b.HasOne("Express.Models.CommissionsRule", "CommissionsRule")
                        .WithMany("CommisstionsRealTimes")
                        .HasForeignKey("IDComR")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bill");

                    b.Navigation("CommissionsRule");
                });

            modelBuilder.Entity("Express.Models.CommissionsRule", b =>
                {
                    b.HasOne("Express.Models.ShipCompany", "ShipCompany")
                        .WithMany("CommissionsRules")
                        .HasForeignKey("IDCompany");

                    b.Navigation("ShipCompany");
                });

            modelBuilder.Entity("Express.Models.Districts", b =>
                {
                    b.HasOne("Express.Models.Provinces", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("Proid");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Express.Models.ShipCompany", b =>
                {
                    b.HasOne("Express.Models.SubDistricts", "SubDistrict")
                        .WithOne("ShipCompany")
                        .HasForeignKey("Express.Models.ShipCompany", "SubDisid");

                    b.Navigation("SubDistrict");
                });

            modelBuilder.Entity("Express.Models.ShipDiscount", b =>
                {
                    b.HasOne("Express.Models.ShipCompany", "ShipCompany")
                        .WithMany("ShipDiscounts")
                        .HasForeignKey("Compid");

                    b.Navigation("ShipCompany");
                });

            modelBuilder.Entity("Express.Models.ShippingFee", b =>
                {
                    b.HasOne("Express.Models.ShipCompany", "ShipCompany")
                        .WithMany("ShippingFees")
                        .HasForeignKey("Compid");

                    b.Navigation("ShipCompany");
                });

            modelBuilder.Entity("Express.Models.SubDistricts", b =>
                {
                    b.HasOne("Express.Models.Districts", "District")
                        .WithMany("SubDistricts")
                        .HasForeignKey("Disid");

                    b.Navigation("District");
                });

            modelBuilder.Entity("Express.Models.Users", b =>
                {
                    b.HasOne("Express.Models.SubDistricts", "SubDistrict")
                        .WithOne("User")
                        .HasForeignKey("Express.Models.Users", "SubDisid");

                    b.Navigation("SubDistrict");
                });

            modelBuilder.Entity("Express.Models.Bill", b =>
                {
                    b.Navigation("CommisstionsRealTime");

                    b.Navigation("StatusDetail");
                });

            modelBuilder.Entity("Express.Models.CommissionsRule", b =>
                {
                    b.Navigation("CommisstionsRealTimes");
                });

            modelBuilder.Entity("Express.Models.Districts", b =>
                {
                    b.Navigation("SubDistricts");
                });

            modelBuilder.Entity("Express.Models.Provinces", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Express.Models.ShipCompany", b =>
                {
                    b.Navigation("CommissionsRules");

                    b.Navigation("ShipDiscounts");

                    b.Navigation("ShippingFees");
                });

            modelBuilder.Entity("Express.Models.SubDistricts", b =>
                {
                    b.Navigation("ShipCompany");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Express.Models.Users", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
